name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '1.8'
        cache: 'sbt'
        cache-dependency-path: | # optional
          build.sbt
          project/build.properties
    - name: Run tests
      run: sbt test
